# Generated by Django 3.0.4 on 2020-03-20 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa')),
                ('url', models.URLField(verbose_name='Url')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('active', models.BooleanField(default=True, verbose_name='Aktywna')),
                ('last_online', models.DateTimeField(blank=True, null=True, verbose_name='Ostatnio online')),
                ('last_check', models.DateTimeField(blank=True, null=True, verbose_name='Ostatnio sprawdzana')),
                ('http_status', models.PositiveIntegerField(blank=True, null=True, verbose_name='Status HTTP')),
                ('hsts_header', models.BooleanField(blank=True, null=True, verbose_name='HSTS')),
                ('delay', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='Opóźnienie')),
                ('delay_avg', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='Opóźnienie')),
                ('ssl_expiry_date', models.DateField(blank=True, null=True, verbose_name='Ważność SSL')),
            ],
            options={
                'verbose_name': 'Strona',
                'verbose_name_plural': 'Strony',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('http_status', models.PositiveIntegerField(blank=True, null=True, verbose_name='Status HTTP')),
                ('hsts_header', models.BooleanField(blank=True, null=True, verbose_name='HSTS')),
                ('delay', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='Opóźnienie')),
                ('ssl_expiry_date', models.DateField(blank=True, null=True, verbose_name='Ważność SSL')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Website')),
            ],
            options={
                'verbose_name': 'Check',
                'verbose_name_plural': 'Checks',
                'ordering': ('-date_created',),
            },
        ),
    ]
